# PolicyScan build for AT_Tower
---
name: $(TeamProject)_$(SourceBranchName)_PolicyScan_$(Date:dd)-$(Date:MM)-$(Date:yyyy)_$(Rev:r)
trigger: none

variables:
  - template: Templates_CI/vars.yml

stages:
  - stage: Build
  
    jobs:
    - job: Workspace_PolicyScan_Execution
      dependsOn: []
      pool: FA_BuildPool-Prod            
      steps:
        - template: Templates_CI/CI_Steps/Nuget_Restore_Step.yml
            
        - template: Templates_CI/CI_Steps/VS_Build_Step.yml

        - template: Templates_CI/CI_Steps/VS_Test_Step.yml

        - template: Templates_CI/CI_Steps/FA_Zip_Step.yml

        - task: FAVeracodeAPI@1
          displayName: 'First American Veracode Upload API'
          inputs:
            ScanOption: PScan
            VeracodeAppName: 'Lender Vendor Integration Services (LVIS)'
            VeracodeAppID: 243990
            EmailRecipients: 'lvis@firstam.com'

        - template: Templates_CI/CI_Steps/Clean_Directories_Step.yml